### ISSUE TITLE
Offer more installation options for different operating systems

### ISSUE THREAD

**Issue by whitep4nth3r** [sailhouse/cli#2]
Currently the only way described on the docs to install Sailhouse is via `brew`. This is only suitable for MacOS users.

<img width="823" alt="image" src="https://github.com/sailhouse/cli/assets/52798353/efe7f6ff-2d13-41f9-83f1-78cdb8a37329">

We should offer more installation methods to serve different operating systems including:

- npm
- yarn
- pnpm

**Comment by estephinson** [comment]
Closed as per discussion in sailhouse/docs#10
